// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Number = sequelize.define('number', {
    id: {
      type: DataTypes.INTEGER,
      field: 'ID',
      primaryKey: true,
      allowNull: false,
    },
    noOfPlayersReg: {
      type: DataTypes.INTEGER,
      field: 'no_of_players_reg',
      allowNull: false,
    },
    noOfWords: {
      type: DataTypes.INTEGER,
      field: 'no_of_words',
      allowNull: false,
    },
  }, {
    tableName: 'number',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Number.associate = (models) => {
  };

  return Number;
};
