// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Quizdata = sequelize.define('quizdata', {
    userId: {
      type: DataTypes.INTEGER,
      field: 'userID',
      primaryKey: true,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
      field: 'Name',
    },
    userpassword: {
      type: DataTypes.STRING,
    },
    email: {
      type: DataTypes.STRING,
      field: 'Email',
      allowNull: false,
    },
    score: {
      type: DataTypes.INTEGER,
      field: 'Score',
    },
    remarks: {
      type: DataTypes.STRING,
      field: 'Remarks',
      allowNull: false,
    },
    count: {
      type: DataTypes.INTEGER,
      field: 'Count',
      allowNull: false,
    },
  }, {
    tableName: 'quizdata',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Quizdata.associate = (models) => {
  };

  return Quizdata;
};
